### ISSUE TITLE
Problems with the package

### ISSUE THREAD

**Issue by booyaa** [aergonaut/languageserver-rust#3]
Hi!

I've installed package (include the nuclide). RLS doesn't appear to be functioning.  I've also tried installing the `atom-languageclient` package incase this was missed out as part of the instructions.

I've got a working version of RLS because I'm also testing vscode and neovim.

I'm not really familiar with atom, so I appreciate there maybe some key strokes to trigger language server functionality. I did expect to see some indicator that the RLS was analysing the code and the ability to hover over definitions.

Is there any logging I can example to diagnose why it's not work?

Thanks!

**Comment by damieng** [comment]
I suspect this might be a problem I've seen with the atom languageclient library it uses. Basically sometimes Atom ends up with multiple grammar objects for the same grammar and the current check didn't expect that and used object equality  https://github.com/atom/atom-languageclient/issues/65

Once that's out (by Monday) a new version of this package will need to go out and all should be fine.

There's never any need to install atom-languageclient directly - it's a dependency used by the language server integration packages.

**Comment by booyaa** [comment]
Ah k, will retest then and see if I can close this issue out. Thanks!

**Comment by aergonaut** [comment]
Thanks @damieng for chiming in! I'll keep an eye on https://github.com/atom/atom-languageclient/issues/65 and update this package.

**Comment by booyaa** [comment]
Updated to v0.3.0 still nothing to indicate this plugin is working with RLS.  I can't get hover, goto definition or even the analysis mode to appear. Furthermore the actual Rust code is being identified as Plain Text rather than Rust file type.

Is there anything else I should try?

**Comment by damieng** [comment]
If rust is being identified as plain text then you'll also need to install
a rust grammar from the Atom package list.

**Comment by booyaa** [comment]
Thanks that fixed it! Also disabling most of the non-rust community packages caused this rust package to start working.
